version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080